# Generated by Django 4.1.5 on 2023-02-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='dbdemo1_employee',
        ),
    ]
