# Generated by Django 4.1.5 on 2023-04-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo1', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': '1.Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
