# Generated by Django 4.1.5 on 2024-10-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo1', '0005_alter_employee_options_employee_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
