# Generated by Django 5.1.3 on 2025-01-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbdemo1', '0006_alter_employee_age_alter_employee_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
